Name: ci
-on:
  push:
    branches: [master]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  pull_request:
    branches: [master]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: npm ci
      - run: npm run build
      - run: npm run format-check
      - run: npm run lint
      - run: npm run test
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
      - uses: actions/upload-artifact@v2
        with:
          name: action.yml
          path: action.yml

  test:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [built, committed]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - if: matrix.target == 'built' || github.event_name == 'pull_request'
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - if: matrix.target == 'built' || github.event_name == 'pull_request'
        uses: actions/download-artifact@v2
        with:
          name: action.yml
          path: .

      - name: Create change
        run: date +%s > report.txt

      - name: Create Pull Request
        id: cpr
        uses: ./
        with:
          commit-message: '[CI] test ${{ matrix.target }}'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: '[CI] test ${{ matrix.target }}'
          body: |
            - CI test case for target '${{ matrix.target }}'

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: ci-test-${{ matrix.target }}

      - name: Close Pull
        uses: peter-evans/close-pull@v1
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          comment: '[CI] test ${{ matrix.target }}'
          delete-branch: true

  commentTestSuiteHelp:
    if: github.event_name == 'pull_request'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Full test suite slash command

      - if: steps.fc.outputs.comment-id == ''
        name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.number }}
          body: |
            Full test suite slash command (repository admin only)
            ```
            /test repository=${{ github.event.pull_request.head.repo.full_name }} ref=${{ github.event.pull_request.head.ref }} build=true
            ```

  package:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: 'build: update distribution'
          title: Update distribution
          body: |
            - Updates the distribution for changes on `master`

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: update-distribution
BEGIN:
GLOW7:
Name: ci
Kind: kite**/*backtrace*log.cache'@bitore.sig/paradice'@moejojojojo/moejojojojo/README.md/readme.MD
npc-debug.log*

# Runtime data
pids
*.pid
*.seed

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage

# nyc test coverage
.nyc_output

# Grunt intermediate storage (http://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# node-waf configuration
.lock-wscript

# Compiled binary addons (http://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules
jspm_packages

# Optional npm cache directory
.npm

# Optional REPL history
.node_repl_history
 21  
LICENSE
@@ -0,0 +1,21 @@
    MIT License

    Copyright (c) Microsoft Corporation. All rights reserved.

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE
 4  
README.md
@@ -0,0 +1,4 @@

# Haikus for Codespaces

This is a quick node project template for demoing Codespaces. It is based off of the [Azure node sample](https://github.com/Azure-Samples/nodejs-docs-hello-world). It's great!!!
 8  
gulpfile.js
@@ -0,0 +1,8 @@
const gulp = require('gulp');
const imagemin = require('gulp-imagemin');

exports.default = () => (
	gulp.src('./raw_images/*')
		.pipe(imagemin())
		.pipe(gulp.dest('./public/images'))
);
 22  
haikus.json
@@ -0,0 +1,22 @@
[
    {
        "text": "rain in seattle,\ndon't forget an umbrella,\nor it will be gloom",
        "image": "puddle_jumper_octodex.jpg"
    },
    {
        "text": "my tunes on repeat,\nit's time for me to dj,\nhave you heard this one?",
        "image": "vinyltocat.jpeg"
    },
    {
        "text": "snow is still falling,\nis it time for apres yet?\nlet's do one more run",
        "image": "snowtocat_final.jpg"
    },
    {
        "text": "beep boop bop beep boop,\ni am robot octocat,\ni think there's a bug",
        "image": "Robotocat.jpeg"
    },
    {
        "text": "same plot as before,\nso why is it still awesome?\ni think it's the hat",
        "image": "linktocat.jpg"
    }
]
 14  
index.js
@@ -0,0 +1,14 @@
let express = require('express');
let app = express();
let ejs = require('ejs');
const haikus = require('./haikus.json');
const port = process.env.PORT || 3000;

app.use(express.static('public'))
app.set('view engine', 'ejs');

app.get('/', (req, res) => {
  res.render('index', {haikus: haikus});
});

app.listen(port);
 7,266  
package-lock.json
Large diffs are not rendered by default.

 21  
package.json
@@ -0,0 +1,21 @@
{
    "name": "app-service-hello-world",
    "description": "Simple Hello World Node.js sample for Azure App Service",
    "version": "0.0.1",
    "private": true,
    "license": "MIT",
    "author": "Microsoft",
    "scripts": {
        "start": "node index.js",
        "dev": "nodemon"
    },
    "dependencies": {
        "ejs": "^3.0.1",
        "express": "^4.17.1",
        "nodemon": "^2.0.2"
    },
    "devDependencies": {
        "gulp": "^4.0.2",
        "gulp-imagemin": "^7.1.0"
    }
}
 13  
process.json
@@ -0,0 +1,13 @@
    {
      "name"        : "worker",
      "script"      : "./index.js",
      "instances"   : 1,
      "merge_logs"  : true,
      "log_date_format" : "YYYY-MM-DD HH:mm Z",
      "watch": true,
      "watch_options": {
        "followSymlinks": true,
        "usePolling"   : true,
        "interval"    : 5
      }
    }
 36  
public/css/main.css
@@ -0,0 +1,36 @@
body {
    background-color: #2a2b2f; 
    display: flex; 
    flex-direction: column;
    justify-content: center; 
    font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif; 
    font-weight: 300;
    color: #fff;
    text-align:center;
}

.mona-images {
    max-width: 400px;
    max-height: 400px;
    border: 8px solid #fff;
}

.haiku-containers {
    padding: 10px 0px 20px 0px;
}

.haikus {
    font-size: 18px;
    white-space: pre-wrap;
}

@media only screen and (max-width: 600px) {
    .june-images {
        max-width: 340px;
        max-height: 340px;
    }

    .haikus {
        font-size: 22px;
    }
}
 BIN +37 KB 
public/images/Robotocat.jpeg
Unable to render rich display

 BIN +52.5 KB 
public/images/linktocat.jpg
Unable to render rich display

 BIN +31.4 KB 
public/images/puddle_jumper_octodex.jpg
Unable to render rich display

 BIN +36.8 KB 
public/images/snowtocat_final.jpg
Unable to render rich display

 BIN +19.8 KB 
public/images/vinyltocat.jpeg
Unable to render rich display

 26  
views/index.ejs
@@ -0,0 +1,26 @@
<!DOCTYPE html>
<html>
  <head>
    <title>Haikus for Mona</title>
    <link href="/css/main.css" rel="stylesheet" type="text/css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:title" content="Haikus for Mona">
    <meta property="og:description" content="Some of the best haikus you'll ever read about our rescue dog June">
    <meta property="og:image" content="/images/sunlight.jpg">
  </head>
  <body>
    <h1>Haikus for Mona</h1>
    <div>
      <% for(var i=0; i < haikus.length; i++) { %>
        <img
          class="mona-images"
          src="images/<%= haikus[i].image %>" />
        <div 
          class="haiku-containers">
          <p 
            class="haikus"
          ><%- haikus[i].text %></p>
        </div>
      <% } %>
    </div>
</html>
 61  
web.config
@@ -0,0 +1,61 @@
<?xml version="1.0" encoding="utf-8"?>
<!--
     This configuration file is required if iisnode is used to run node processes behind
     IIS or IIS Express.  For more information, visit:
     https://github.com/tjanczuk/iisnode/blob/master/src/samples/configuration/web.config
-->

<configuration>
  <system.webServer>
    <!-- Visit http://blogs.msdn.com/b/windowsazure/archive/2013/11/14/introduction-to-websockets-on-windows-azure-web-sites.aspx for more information on WebSocket support -->
    <webSocket enabled="false" />
    <handlers>
      <!-- Indicates that the server.js file is a node.js site to be handled by the iisnode module -->
      <add name="iisnode" path="index.js" verb="*" modules="iisnode"/>
    </handlers>
    <rewrite>
      <rules>
        <!-- Do not interfere with requests for node-inspector debugging -->
        <rule name="NodeInspector" patternSyntax="ECMAScript" stopProcessing="true">
          <match url="^index.js\/debug[\/]?" />
        </rule>

        <!-- First we consider whether the incoming URL matches a physical file in the /public folder -->
        <rule name="StaticContent">
          <action type="Rewrite" url="public{REQUEST_URI}"/>
        </rule>

        <!-- All other URLs are mapped to the node.js site entry point -->
        <rule name="DynamicContent">
          <conditions>
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="True"/>
          </conditions>
          <action type="Rewrite" url="index.js"/>
        </rule>
      </rules>
    </rewrite>

    <!-- 'bin' directory has no special meaning in node.js and apps can be placed in it -->
    <security>
      <requestFiltering>
        <hiddenSegments>
          <remove segment="bin"/>
        </hiddenSegments>
      </requestFiltering>
    </security>

    <!-- Make sure error responses are left untouched -->
    <httpErrors existingResponse="PassThrough" />

    <!--
      You can control how Node is hosted within IIS using the following options:
        * watchedFiles: semi-colon separated list of files that will be watched for changes to restart the server
        * node_env: will be propagated to node as NODE_ENV environment variable
        * debuggingEnabled - controls whether the built-in debugger is enabled
      See https://github.com/tjanczuk/iisnode/blob/master/src/samples/configuration/web.config for a full list of options
    -->
    <!--<iisnode watchedFiles="web.config;*.js"/>-->
  </system.webServer>
</configuration>
